# Generated by Django 5.2.13 on 2026-05-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_delete_analytics_remove_job_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='package',
            field=models.CharField(choices=[('INSTANT', 'Instant'), ('PRO', 'Pro')], default='INSTANT', max_length=10),
        ),
    ]
